controller_manager:
  ros__parameters:
    update_rate: 100

    rtp_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_broadcaster:
      type: velocity_controllers/JointGroupVelocityController



rtp_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    publish_rate: 50.0
    wheel_radius: 0.5026
    wheel_seperation: 0.79
    # left_wheel_radius_multiplier:
    # right_wheel_radius_multiplier:
    # wheel_seperation_multiplier:

    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true
    

    linear:
      x:
         has_velocity_limits: true
         max_velocity: 0.5
         min_velocity: -0.5
         has_acceleration_limit: true
         max_acceleration: 0.1
         min_acceleration: -0.1
         has_jerk_limits: false

    
    angular:
      z:
         has_velocity_limits: true
         max_velocity: 0.5
         min_velocity: -0.5
         has_acceleration_limit: true
         max_acceleration: 0.1
         min_acceleration:  -0.1
         has_jerk_limits: false

# wheel_velocity_broadcaster:
#   ros__parameters:
#     joints:
#       - left_wheel_joint
#       - right_wheel_joint



    